### ISSUE TITLE
Suggestion: Add packet capture to the cheat sheet.

### ISSUE THREAD

**Issue by unixtreme** [CompassSecurity/Hacking_Tools_Cheat_Sheet#1]
While Nmap is handy a packet capture can help find software being used, protocols, and often their versions. All of which can help find vulnerable targets. 

e.g. a quick packet capture could show you servers using SMB1.0 which doesn't support encryption, allowing you to capture information over the wire.

**Comment by emanuelduss** [comment]
Hi

Thanks for your input. We already cover nmap for scanning and tcpdump/wireshark for packet capture. I think adding how to detect SMB1 via a packet capture is a bit too specific for this cheat sheet. Nmap does already some version detection using the version detection engine and the nmap NSE scripts. This is already included in the cheat sheet.

have a good time,
Emanuel
